window.poem = [
  {string:"What are you doing", rp:true},{string:"I might be the biggest fan you ever had", rp:true},{string:"Wow", rp:false},{string:"I think im back", rp:false},{string:"The land of the living welcomes me", rp:true},{string:":)", rp:false},{string:"I WANT you all up in my ribcage pls", rp:false},{string:"Tryularly", rp:false},
  {string:"*regularly", rp:true},
  {string:"Don\'t go somewhere I cant follow", rp:true},
  {string:"you\'re on the verge", rp:false},
  {string:"Oh", rp:false},
  {string:"No I HEAR that", rp:false},
  {string:"I spent an hour last night", rp:false},
  {string:"Following those", rp:true},
  {string:"Hahahah", rp:false},
  {string:"And then it says", rp:false},
  {string:"\"Welcome, mara\"", rp:false},
  {string:"And if I pull away too fast it will yell", rp:false},
  {string:"At me", rp:false},
  {string:"I know how this shit", rp:false},
  {string:"Goes", rp:false},
  {string:"I can imagine it", rp:true},
  {string:"You are leaving me here", rp:true},
  {string:"Nevermind", rp:false},
  {string:"You\'re a complete freak", rp:true},
  {string:"So I have a new dream", rp:true},
  {string:"wHich is for you o explain this to me", rp:false},
  {string:"out loud when I get to my bed", rp:false},
  {string:"I think id sleep so well", rp:true},
  {string:"I knew it", rp:false},
  {string:"I knew it.", rp:false}
];

window.response = [
  {string:"I spend a little over 6 hours a week in the building where the atomic bomb was created", rp:true},
  {string:"U are an arrow and it points straight at my chest",rp:false},
  {string:"I am making an arrow and I\'m going to point it at your chest right in the center",rp:true},
  {string:"I\'m not back",rp:false},
  {string:"I want to press my nose into your ribcage",rp:true},
  {string:"\"I might be the biggest fan you ever had\"",rp:false},
  {string:"this text is now an object in my mind, it is a vector that points to a red X on my chest",rp:true},
  {string:"The red X is the father of all the special points on my body like the centers of my wrists and creases in my elbows and the lines that connect them",rp:true},
  {string:"All cumulating about the point X on my chest and you are a red arrow that is oriented at a right angle right on the X ready to be pushed in",rp:false},
  {string:"Pushing you into me will feel like plugging in a USB drive",rp:false},
  {string:"After fumbling to find the correct orientation (one or two tries) the USB stick is pushed in, a green light goes on",rp:true},
  {string:"There is a scenario where I face you head on",rp:false},
  {string:"We are both vector arrows facing each other at the origin",rp:false},
  {string:"I am standing in front of a mirror and my nose touches its surface",rp:false},
  {string:"The point where my nose touches the mirror is a point of interest",rp:true},
  {string:"Rather than my reflection your nose meets mine here at this point which is the origin",rp:false},
  {string:"origin x,y,z = 0,0,0",rp:true},
  {string:"We are a function symmetrical about the xz plane every move I make you mirror perfectly despite some constant scaling factor, perhaps",rp:false},
  {string:"We are straight arrows again and we are still",rp:false},
  {string:"The marriage of two numbers must be a multiplication, not addition",rp:false},
  {string:"The marriage of two arrows is the cross product of vector 1 and vector 2",rp:false},
  {string:"Oriented about each other by the angle 180 degrees which coincides with the mirror reflection scenario",rp:false},
  {string:"There are 180 degrees between us (mirror reflection) so our mathematical marriage evaluates to negative zero which is the same as zero",rp:false},
  {string:"This is when you are the mirror reflection of me and to come to you I run at the mirror, which causes you to run at the mirror and we collide then cancel each other out entirely by geometry of reflection",rp:true},
  {string:"So to one observing the mirror there is nothing left but where did we go?? I am with you, I ran at you you ran at me as we saw, we are clearly somewhere else",rp:true},
  {string:"This scenario is observed when we both are on a piece of paper on a desk",rp:false},
  {string:"You are on the left and I am on the right (we are both drawn, our domain is two dimensional in this case)",rp:false},
  {string:"To make every surface of my body meet every surface of your body the paper is folded by an observer directly above the desk, paper folded down the middle line that divides us (this is what the mirror used to be)",rp:false},
  {string:"But the observer folds up each side at an equal rate, the centerfold remains on the desk.",rp:false},
  {string:"So to the observer the two dimensional paper world which is you and me grows smaller until it is folded and creased.",rp:false},
  {string:"You and I meet, two halves of the one paper pressed together and the paper is folded and is perpendicular to the desk surface, and the observer, who is directly above, only sees the differentially thin edge of the folded paper, which is very thin so for practical purposes the observer no can no longer see us due to the paper\'s vertical orientation and its infinite thinness. This is how we disappear together",rp:true}
];
